### ISSUE TITLE
[feature request] Dropdown filters

### ISSUE THREAD

**Issue by aweller** [kayak/react-tisch#2]
The string filter works fine, but only allows one filter at a time. An option to add a dropdown menu to the top of a (categorical) column to only show rows with the selected category would be an easy way to allow complex filters. Datatables.js implements such a dropdown filter.

**Comment by remiremi** [comment]
This is possible by passing the `filter` prop to the column you want the filter on. See the "Eye color" column in the demo: https://kayak.github.io/react-tisch/examples/index.html
